### ISSUE TITLE
Convert OB Annex 1000: Service restrictions 15/03/2012

### ISSUE THREAD

**Issue by ronaldtse** [ituob/service-publications-data#10]
https://github.com/ituob/service-publications-refs/tree/master/1000-SR.1

**Comment by manuelfuenmayor** [comment]
Added in https://github.com/ituob/service-publications-refs/pull/3

**Comment by ronaldtse** [comment]
Moved here in ae0f5ac44c9b8a8f6137c26300e43b530d3f57b8
