### ISSUE TITLE
Convert List of ITU Carrier Codes (ICCs) (https://www.itu.int/oth/T0201/en)

### ISSUE THREAD

**Issue by ronaldtse** [ituob/service-publications-data#14]
List of ITU Carrier Codes (ICCs) (https://www.itu.int/oth/T0201/en)

**Comment by anermina** [comment]
Can you please check if markup is fine for the attached document and let me know if any changes are needed? There are a lot of documents of this kind and I would like to make sure that conversion to AsciiDoc is done properly before I proceed converting the other documents. 
[iccs.zip](https://github.com/ituob/service-publications-data/files/3929348/iccs.zip)

**Comment by ronaldtse** [comment]
@anermina Thanks for this. In fact, it would be easier to change it to Excel (and CSV format), @strogonoff will need to come up with a normalized message form for each entry.

Could you help extract out the data into a spreadsheet then? Thanks!

**Comment by ronaldtse** [comment]
Done in `ICCs/icc-completed.xlsx`. Pending conversion to YAML.

**Comment by ronaldtse** [comment]
Completed conversion to YAML.
