### ISSUE TITLE
Convert List of Recognized Operating Agencies (ROAs) (https://www.itu.int/oth/T0204)

### ISSUE THREAD

**Issue by ronaldtse** [ituob/service-publications-data#15]
List of Recognized Operating Agencies (ROAs) (https://www.itu.int/oth/T0204)

**Comment by ronaldtse** [comment]
@manuel489 

These are not documents, so just copy paste them into Excel would already work.

We probably don't really need to input the language translations for ROA, because it's only the country name, column names that are translated.

**Comment by manuelfuenmayor** [comment]
Added PR in https://github.com/ituob/service-publications-data/pull/19

**Comment by ronaldtse** [comment]
Done in ROA.xlsx, pending conversion to YAML.

**Comment by ronaldtse** [comment]
Completed conversion to YAML.
