### ISSUE TITLE
Convert Bureaufax Table (https://www.itu.int/en/ITU-T/inr/Pages/bureaufax.aspx)

### ISSUE THREAD

**Issue by ronaldtse** [ituob/service-publications-data#16]
Bureaufax Table (https://www.itu.int/en/ITU-T/inr/Pages/bureaufax.aspx)

**Comment by ronaldtse** [comment]
@manuel489 for these documents, can you extract them into YAML (header) and Excel/CSV (body)? Thanks!

**Comment by manuelfuenmayor** [comment]
Added first pass for Algeria in https://github.com/ituob/service-publications-data/pull/26

**Comment by manuelfuenmayor** [comment]
Added YAML and CSV files for the rest of the countries in https://github.com/ituob/service-publications-data/pull/26

**Comment by ronaldtse** [comment]
Completed normalization.
