### ISSUE TITLE
Convert ITU OB Annex at issue 669, F.1

### ISSUE THREAD

**Issue by ronaldtse** [ituob/service-publications-data#2]
Here are the documents:
https://github.com/ituob/service-publications-refs/tree/master/669-F.1

@anermina, could you please help convert this to a syntax similar to Metanorma and push it here? Thanks!

**Comment by anermina** [comment]
Sure, no problem.

**Comment by ronaldtse** [comment]
@anermina what's the status on this? Thanks!

**Comment by ronaldtse** [comment]
ping @strogonoff

**Comment by anermina** [comment]
It's almost finished. I'll upload the files later today, as soon as I get back home

**Comment by ronaldtse** [comment]
@anermina I noticed the files have been uploaded, are they all good? If so let's close this task. Thanks!

**Comment by anermina** [comment]
@ronaldtse Yes, they are converted to AsciiDoc, so we can close this task.

**Comment by ronaldtse** [comment]
Thanks @anermina !
