### ISSUE TITLE
Convert OB Annex 978: List of Telex Destination Codes (TDC) and Telex Network Identification Codes (TNIC) 15/04/2011 F.68 / F.69

### ISSUE THREAD

**Issue by ronaldtse** [ituob/service-publications-data#7]
https://github.com/ituob/service-publications-refs/tree/master/978-F.68

**Comment by manuelfuenmayor** [comment]
Added in https://github.com/ituob/service-publications-refs/pull/1

**Comment by ronaldtse** [comment]
Moved here in ae0f5ac44c9b8a8f6137c26300e43b530d3f57b8.
