### ISSUE TITLE
Convert OB Annex 980: List of telegram destination indicators 15/05/2011 F.32

### ISSUE THREAD

**Issue by ronaldtse** [ituob/service-publications-data#8]
https://github.com/ituob/service-publications-refs/tree/master/980-F.32

**Comment by manuelfuenmayor** [comment]
Added English doc in https://github.com/ituob/service-publications-data/pull/20

**Comment by manuelfuenmayor** [comment]
Added French and Spanish version along with some corrections in https://github.com/ituob/service-publications-data/pull/20

**Comment by ronaldtse** [comment]
Converted to T-SP-F.400-2011.xlsx , pending conversion to YAML.

**Comment by ronaldtse** [comment]
Completed conversion to YAML.
