### ISSUE TITLE
Convert OB Annex 991: Call-Back and alternative calling procedures (Res. 21 Rev. PP-2006) 01/11/2011 Res. 21 PP-2006

### ISSUE THREAD

**Issue by ronaldtse** [ituob/service-publications-data#9]
https://github.com/ituob/service-publications-refs/tree/master/991-PP.RES.21.pp

**Comment by manuelfuenmayor** [comment]
Added in https://github.com/ituob/service-publications-refs/pull/2

**Comment by ronaldtse** [comment]
Moved here in ae0f5ac44c9b8a8f6137c26300e43b530d3f57b8.
